name: selcald
dependencies:
- cairo=1.12.18=5
- cython=0.23.4=py27_0
- decorator=4.0.4=py27_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- ipython=4.0.0=py27_0
- ipython_genutils=0.1.0=py27_0
- libgfortran=1.0=0
- libpng=1.6.17=0
- libxml2=2.9.2=0
- matplotlib=1.4.3=np110py27_2
- numpy=1.10.1=py27_0
- openblas=0.2.14=3
- openssl=1.0.2d=0
- pandas=0.17.0=np110py27_0
- path.py=8.1.2=py27_0
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pip=7.1.2=py27_0
- pixman=0.26.2=0
- py2cairo=1.10.0=py27_2
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_0
- python=2.7.10=2
- python-dateutil=2.4.2=py27_0
- pytz=2015.6=py27_0
- qt=4.8.7=1
- readline=6.2=2
- scipy=0.16.0=np110py27_1
- setuptools=18.4=py27_0
- simplegeneric=0.8.1=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- traitlets=4.0.0=py27_0
- wheel=0.26.0=py27_1
- zlib=1.2.8=0
- pip:
  - behave==1.2.5
  - enum34==1.0.4
  - ipython-genutils==0.1.0
  - parse==1.6.6
  - parse-type==0.3.4
  - pyaudio==0.2.9
  - wavefile==1.3
