name: selcald
dependencies:
- anaconda-client=1.0.2=py27_0
- appnope=0.1.0=py27_0
- clyent=0.4.0=py27_0
- cython=0.23.4=py27_0
- decorator=4.0.4=py27_0
- freetype=2.5.5=0
- ipython=4.0.0=py27_1
- ipython_genutils=0.1.0=py27_0
- jpeg=8d=1
- libpng=1.6.17=0
- libtiff=4.0.6=0
- matplotlib=1.4.3=np110py27_3
- numpy=1.10.1=py27_0
- openssl=1.0.2d=0
- pandas=0.17.0=np110py27_0
- path.py=8.1.2=py27_0
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pillow=3.0.0=py27_1
- pip=7.1.2=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_0
- python=2.7.10=2
- python-dateutil=2.4.2=py27_0
- python.app=1.2=py27_4
- pytz=2015.6=py27_0
- pyyaml=3.11=py27_1
- qt=4.8.7=1
- readline=6.2=2
- requests=2.8.1=py27_0
- scipy=0.16.0=np110py27_1
- setuptools=18.4=py27_0
- simplegeneric=0.8.1=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- traitlets=4.0.0=py27_0
- wheel=0.26.0=py27_1
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - bidict==0.9.0.post1
  - ipython-genutils==0.1.0
  - pyaudio==0.2.9
  - scikits.audiolab==0.11.0
  - wave==0.0.2
  - wavefile-1.5==git
